# global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ios-challenge' do
    # Pods for tsjacdmx
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'

  target 'ios-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-challengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
